function A12 = simulinkA12(p,q1,q2,q3,q4)
%SIMULINKA12
%    A12 = SIMULINKA12(P,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2020 12:53:05

t2 = cos(p);
t3 = sin(p);
t4 = p+q1;
t5 = p+q3;
t6 = cos(t4);
t7 = cos(t5);
t8 = q2+t4;
t9 = q4+t5;
t10 = sin(t4);
t11 = sin(t5);
t16 = t2.*3.13e-2;
t17 = t3.*3.13e-2;
t12 = cos(t8);
t13 = cos(t9);
t14 = sin(t8);
t15 = sin(t9);
t18 = -t16;
t19 = -t17;
t20 = t6.*2.8333e-1;
t21 = t7.*2.8333e-1;
t22 = t10.*2.8333e-1;
t23 = t11.*2.8333e-1;
t24 = -t20;
t25 = -t21;
t26 = -t22;
t27 = -t23;
t28 = t12.*2.38008e-1;
t29 = t13.*2.38008e-1;
t30 = t14.*2.38008e-1;
t31 = t15.*2.38008e-1;
t32 = -t28;
t33 = -t29;
t34 = -t30;
t35 = -t31;
A12 = reshape([t24+t32,t26+t34,0.0,0.0,t32,t34,0.0,0.0,0.0,0.0,t25+t33,t27+t35,0.0,0.0,t33,t35,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,t18+t24+t32,t19+t26+t34,t18+t25+t33,t19+t27+t35],[4,7]);
