%% This script generates a linearized symbolic state space model
% It assumes that certain variables already exist in the MATLAB workspace,
% namely ones generated by Monkey5Link_SM_mrt.m (ddq1, ddq2, associated
% syms, etc.)

load("HybridMonkeyDynamics.mat");

eqns = [dq; ddq1];
states = [q; dq];
disp("Calculating A Matrix")
A_ss = jacobian(eqns, states);
disp("Simplifying A")
A_ss = simplify(A_ss);
disp("Done with A");

inputs = [u1; u2; u3; u4];
disp("Calculating B Matrix")
B_ss = jacobian(eqns, inputs);
disp("Simplifying B")
A_ss = simplify(B_ss);
disp("Done with B");