function ddq = pendulum_dyn(dq1,dq2,q1,q2,tau1,tau2)
%PENDULUM_DYN
%    DDQ = PENDULUM_DYN(DQ1,DQ2,Q1,Q2,TAU1,TAU2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Apr-2020 16:24:32

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q2);
t5 = q1+q2;
t6 = dq1.^2;
t10 = -tau2;
t7 = t3+1.0;
t8 = t3.^2;
t9 = cos(t5);
t11 = t2.*2.0e+1;
t12 = t4.*t6;
t13 = -t11;
t14 = t9.*1.0e+1;
t15 = t8-2.0;
t16 = -t14;
t17 = 1.0./t15;
t18 = t10+t12+t14;
ddq = [-t17.*(t13+t16+tau1+dq2.*t4.*(dq1+dq2)+dq1.*dq2.*t4)-t7.*t17.*t18;t7.*t17.*(t13+t16+tau1+dq2.^2.*t4+dq1.*dq2.*t4.*2.0)+t17.*t18.*(t7.*2.0+1.0)];
